TrajectoryPlannerROS:

  #Robot Configuration
#  acc_lim_x: 0.5
#  acc_lim_y: 0
#  acc_lim_th: 1.0
  max_vel_x: 0.5
  min_vel_x: 0.2
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.4
  escape_vel: -0.2
  holonomic_robot: false
  
  #Goal Tolerance
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.10
#  latch_xy_goal_tolerance: false
  
  #Forward Simulation
  sim_time: 2.0 #HARLIE: 2.0
#  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 16.0
  
  #Trajectory Scoring
  path_distance_bias: 0.1
  goal_distance_bias: 1.2
  occdist_scale: 0.02
#  heading_lookahead: 0.5
#  heading_scoring: false
  dwa: true
  publish_cost_grid_pc: true
  
  #Oscillation Prevention Parameters
#  oscillation_reset_dist: 0.2
