TrajectoryPlannerROS:

  #Robot Configuration
  acc_lim_x: 0.1
  acc_lim_y: 0
  acc_lim_th: 0.1
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 1.57
  min_in_place_rotational_vel: 0.1
  holonomic_robot: false
  
  #Goal Tolerance
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true
  
  #Forward Simulation
  sim_time: 2.0
  vx_samples: 3
  vtheta_samples: 20
  
  #Trajectory Scoring
  path_distance_bias: 5.0
  goal_distance_bias: 0.8
  occdist_scale: 0.05
  heading_scoring: false
  dwa: false
