local_costmap:
  #Coordinate Frame/TF
  global_frame: /odom
  transform_tolerance: 0.35
  
  #Rate
  update_frequency: 10.0
  publish_frequency: 1.0
  
  #Map Management
  static_map: false
  rolling_window: true
  width: 12.0
  height: 12.0
  resolution: 0.05
