#Coordinate Frame/TF
robot_base_frame: /base_link

#Global
obstacle_range: 5.0
raytrace_range: 6.0 
#Scale the exponential decay so that it is basically a step function that drops to 0 at the inflation radius
cost_scaling_factor: 10.0 #11.8

#Robot Description
inflation_radius: 0.5
#WARNING: footprint assumes arm is in stowed position
footprint: [
  [-0.292, -0.370],
  [ 0.916, -0.370],
  [ 0.916, -0.184],
  [ 1.153, -0.184],
  [ 1.153,  0.055],
  [ 0.909,  0.135],
  [ 0.550,  0.135],
  [ 0.550,  0.322],
  [-0.292,  0.322]
]

#Sensors
observation_sources: "base_laser1 kinect"
base_laser1: {
  sensor_frame: base_laser1_link, 
  data_type: LaserScan, 
  topic: /base_laser1_scan, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 0.5, 
  min_obstacle_height: 0.2
}
kinect: {
  sensor_frame: 
  camera/camera_depth_frame, 
  data_type: PointCloud2, 
  topic: /camera/depth_registered/points, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 2.0, 
  min_obstacle_height: 0.1
}
bounding_box: {
  sensor_frame: bounding_box, 
  data_type: PointCloud, 
  topic: /bounding_box, 
  marking: true, 
  clearing: false, 
  obstacle_range: 400.0, 
  max_obstacle_height: 2.0, 
  min_obstacle_height: 1.8
}

#Map Type
map_type: voxel



