# Configure a joystick for teleoperation of the robot model

# Diff Drive Controller
axis_linear: 1
scale_linear: 1.0
scale_linear_turbo: 2

axis_angular: 0
scale_angular: 2.0
scale_angular_turbo: 2

enable_button: 0  # Trigger
enable_turbo_button: 1  # L1 shoulder button
