hand_description:
  irb_120:
    hand_frame: gripper_body
    robot_frame: base_link
    attached_objects_name: attached
    attach_link: gripper_jaw_1
    hand_group_name: gripper
    arm_group_name: irb_120
    hand_joints: [gripper_jaw_1, gripper_jaw_2]
    hand_touch_links: [gripper_jaw_1, gripper_jaw_2]
    hand_fingertip_links: [gripper_jaw_1, gripper_jaw_2]
    hand_approach_direction: [1.0,0.0,0.0]
    arm_joints: [joint1, joint2, joint3, joint4, joint5, joint6]
